Frontendfixes
HeyHoProBro/HospitalHorror pull request #35
Opened 2018-05-11 19:44 UTC by Seblerr

Made some small changes to frontend, some of which were requested by customer.

2018-05-11 23:06 UTC, delta-one requested changes
Generally, it looks good.

But there is one thing that I don't like: When you load the form to craete a patient (`/createpatientform/:id`), it doesn't seem logical IMO, that you would need an id for that. Because that would mean loading different forms or so depending on a context. If you need the userid, get it from the session-object in the backend and don't make it part of the URL.

Also, as you have pointed out, the Add-button might need a cosmetic upgrade, but we can address that later.

2018-05-12 06:39 UTC, Seblerr commented
You're right. I can fix that today.

Den lör 12 maj 2018 01:06Patrick Franz <notifications@github.com> skrev:

> *@delta-one* requested changes on this pull request.
>
> Generally, it looks good.
>
> But there is one thing that I don't like: When you load the form to craete
> a patient (/createpatientform/:id), it doesn't seem logical IMO, that you
> would need an id for that. Because that would mean loading different forms
> or so depending on a context. If you need the userid, get it from the
> session-object in the backend and don't make it part of the URL.
>
> Also, as you have pointed out, the Add-button might need a cosmetic
> upgrade, but we can address that later.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HeyHoProBro/HospitalHorror/pull/35#pullrequestreview-119602125>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANi5560j9XJ10R9tG9R8NZJkhzML2QLPks5txhl5gaJpZM4T7-AT>
> .
>

2018-05-12 09:14 UTC, delta-one approved these changes

2018-05-13 11:12 UTC, Amaarillo approved these changes

2018-05-13 11:14 UTC, merged